name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: 'E2E_TESTS'

    # C'est ici qu'on définit le dossier de travail par défaut pour toutes les commandes 'run'
    defaults:
      run:
        working-directory: ./siamois-e2e

    steps:
      # 1. Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4

        with:
          node-version: '20'
          cache: 'npm'
          # Important : on spécifie le chemin du fichier lock pour le cache
          cache-dependency-path: siamois-e2e/package-lock.json

      # 3. Installation des dépendances (dans le sous-dossier grâce au 'defaults')
      - name: Install dependencies
        run: npm ci

      # 4. Installation des navigateurs Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        env:
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

      # 5. Exécution des tests
      - name: Run Playwright tests
        run: npx playwright test